import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    include: ["src/**/*.test.ts"],
    exclude: ["node_modules", ".next"],
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary", "lcov"],
      reportsDirectory: "./coverage",
      include: ["src/lib/**", "src/hooks/**"],
      exclude: [
        "src/lib/blog-posts*.ts",
        "src/lib/countries.ts",
        "src/lib/country-brokers.ts",
        "src/lib/import-guides.ts",
        "src/lib/release-notes.ts",
        "src/lib/metrics.ts",
        "src/lib/gtag.ts",
        "src/lib/native-haptics.ts",
        "src/lib/native-splash.ts",
        "src/lib/types.ts",
        "src/lib/locales/**",
        "src/lib/db/migrations.ts",
        "src/lib/tax/**",
        "src/lib/initial-data.ts",
        "src/lib/feature-registry.ts",
        "src/lib/financial-calculations.ts",
        "src/lib/rebalance-calculations.ts",
        "src/lib/crash-scenarios.ts",
        "src/lib/health-score.ts",
        "src/lib/backtest.ts",
        "src/lib/support-knowledge.ts",
        "src/lib/notification-templates.ts",
        "src/lib/email-notifications.ts",
        "src/lib/paywall-nudge.ts",
        "src/lib/with-metrics.ts",
        "src/lib/cron-logging.ts",
        "src/lib/grafana-push.ts",
        "src/lib/web-push.ts",
        "src/lib/whatsapp.ts",
        "src/lib/task-runner.ts",
        "src/lib/turnstile.ts",
        "src/lib/snaptrade-csv-parser.ts",
        "src/lib/snaptrade-client.ts",
        "src/lib/market-hours.ts",
        "src/lib/api-providers/finnhub-news.ts",
        "src/lib/api-providers/fmp.ts",
        "src/lib/api-providers/response.ts",
        "src/lib/api-providers/types.ts",
        "src/lib/api-providers/quota-helpers.ts",
        "src/lib/services/**",
        "src/lib/hooks/**",
        "src/lib/db/seed.ts",
        "src/lib/db/screener.ts",
        "src/lib/db/calendar-events.ts",
        "src/lib/db/device-interest.ts",
        "src/lib/db/feedback.ts",
        "src/lib/db/goals.ts",
        "src/lib/db/holdings-snapshot.ts",
        "src/lib/db/passkeys.ts",
        "src/lib/db/push-subscriptions.ts",
        "src/lib/db/rate-limits.ts",
        "src/lib/db/rebalance.ts",
        "src/lib/db/snaptrade-connections.ts",
        "src/lib/db/support-chat.ts",
        "src/lib/db/watchlist.ts",
        "src/lib/db/analytics.ts",
        "src/hooks/import-types.ts",
        "src/hooks/use-native.ts",
        "src/hooks/use-track.ts",
        "src/hooks/useAds.ts",
        "src/hooks/useCommandSpotlight.ts",
        "src/lib/alert-dispatcher.ts",
        "src/lib/api-cache.ts",
        "src/lib/blog.ts",
        "src/lib/capacitor.ts",
        "src/lib/dividend-scenarios.ts",
        "src/lib/email-template.ts",
        "src/lib/loan-calculations.ts",
        "src/lib/platform-features.ts",
        "src/lib/retirement-calculations.ts",
        "src/lib/simple-csv-parser.ts",
        "src/lib/db/gamifications.ts",
        "src/lib/**/*.tsx",
        "src/lib/broker-parsers/**",
        "src/lib/db/client.ts",
        "src/lib/__tests__/**",
        "src/lib/derive-holdings.ts",
        "src/lib/crypto.ts",
      ],
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
});
