#!/usr/bin/env tsx
/**
 * Generate the contents of knowledge/generated/ from source code.
 *
 * Outputs:
 *   - knowledge/generated/db-schema.md   (tables declared in migrations)
 *   - knowledge/generated/api-surface.md (every route.ts under src/app/api)
 *   - knowledge/generated/cron-registry.md (from src/lib/cron-registry.ts)
 *   - knowledge/generated/feature-flags.md (from feature-flag registry, if present)
 *   - knowledge/generated/skills-index.md (from .cursor/skills/*)
 *
 * Invoked via `npm run knowledge:gen`.
 *
 * This file is deliberately zero-dep (no Zod, no DB import) so it can run in
 * a lint-only environment.
 */

import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(__dirname, "..");
const OUT = join(ROOT, "knowledge", "generated");

function ensureDir(p: string) {
  mkdirSync(p, { recursive: true });
}

function walk(dir: string, filter: (p: string) => boolean, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    const s = statSync(p);
    if (s.isDirectory()) {
      if (entry === "node_modules" || entry === ".next" || entry.startsWith(".")) continue;
      walk(p, filter, out);
    } else if (filter(p)) {
      out.push(p);
    }
  }
  return out;
}

function writeHeader(title: string): string {
  // NOTE: keep this output deterministic. The CI job `knowledge-lint.yml` runs
  // `npm run knowledge:gen` and fails on any diff, so including a timestamp
  // here would make the check fail on every push.
  return [
    `# ${title}`,
    "",
    "> Auto-generated by `npm run knowledge:gen` from source.",
    "> Do not edit by hand.",
    "",
  ].join("\n");
}

function genDbSchema() {
  const file = join(ROOT, "src/lib/db/migrations.ts");
  const src = readFileSync(file, "utf8");
  const re = /CREATE TABLE IF NOT EXISTS (\w+)\s*\(/gi;
  const names = new Set<string>();
  for (const m of src.matchAll(re)) names.add(m[1]);
  const lines = [writeHeader("Database schema (table index)"), ""];
  lines.push(`Source: [\`src/lib/db/migrations.ts\`](../../src/lib/db/migrations.ts)`);
  lines.push("");
  lines.push("| Table | Data access module |");
  lines.push("|-------|--------------------|");
  for (const name of [...names].sort()) {
    const mod = existsAccess(name);
    lines.push(`| \`${name}\` | ${mod ? `[\`${mod}\`](../../${mod})` : "—"} |`);
  }
  writeFileSync(join(OUT, "db-schema.md"), lines.join("\n"));
}

function existsAccess(table: string): string | null {
  const dir = join(ROOT, "src/lib/db");
  for (const entry of readdirSync(dir)) {
    if (!entry.endsWith(".ts") || entry.endsWith(".test.ts")) continue;
    const p = join(dir, entry);
    const src = readFileSync(p, "utf8");
    if (src.includes(table)) return relative(ROOT, p);
  }
  return null;
}

function genApiSurface() {
  const apiDir = join(ROOT, "src/app/api");
  const routes = walk(apiDir, (p) => p.endsWith("/route.ts") || p.endsWith("/route.tsx"));
  const rows: Array<{ path: string; methods: string[]; file: string }> = [];
  for (const file of routes) {
    const src = readFileSync(file, "utf8");
    const methods: string[] = [];
    for (const m of ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]) {
      if (new RegExp(`export\\s+async\\s+function\\s+${m}\\b`).test(src) ||
          new RegExp(`export\\s+const\\s+${m}\\s*=`).test(src) ||
          new RegExp(`export\\s+{[^}]*\\b${m}\\b[^}]*}`).test(src)) {
        methods.push(m);
      }
    }
    const rel = relative(ROOT, file);
    const apiPath = "/" + relative(apiDir, file).replace(/\\/g, "/").replace(/\/route\.tsx?$/, "");
    rows.push({ path: "/api" + apiPath, methods, file: rel });
  }
  rows.sort((a, b) => a.path.localeCompare(b.path));
  const lines = [writeHeader("API surface"), ""];
  lines.push(`${rows.length} routes.`);
  lines.push("");
  lines.push("| Route | Methods | Source |");
  lines.push("|-------|---------|--------|");
  for (const r of rows) {
    lines.push(`| \`${r.path}\` | ${r.methods.join(", ") || "—"} | [\`${r.file}\`](../../${r.file}) |`);
  }
  writeFileSync(join(OUT, "api-surface.md"), lines.join("\n"));
}

function genCronRegistry() {
  const file = join(ROOT, "src/lib/cron-registry.ts");
  const src = readFileSync(file, "utf8");
  const re =
    /{\s*name:\s*"(?<name>[^"]+)",\s*path:\s*"(?<path>[^"]+)",\s*schedule:\s*"(?<schedule>[^"]+)",\s*description:\s*"(?<description>[^"]+)"(?:,\s*paused:\s*(?<paused>true))?/g;
  const lines = [writeHeader("Cron registry"), ""];
  lines.push(
    "Source: [`src/lib/cron-registry.ts`](../../src/lib/cron-registry.ts). Active schedules must match `vercel.json`; entries with `paused: true` are intentionally omitted from Vercel crons.",
  );
  lines.push("");
  lines.push("| Name | Schedule | Path | Description |");
  lines.push("|------|----------|------|-------------|");
  for (const m of src.matchAll(re)) {
    const { name, path, schedule, description, paused } = m.groups as Record<string, string>;
    const sched = paused === "true" ? `**paused** (was \`${schedule}\`)` : `\`${schedule}\``;
    lines.push(`| \`${name}\` | ${sched} | \`${path}\` | ${description} |`);
  }
  writeFileSync(join(OUT, "cron-registry.md"), lines.join("\n"));
}

function genFeatureFlags() {
  const file = join(ROOT, "src/lib/db/settings.ts");
  const src = readFileSync(file, "utf8");
  const block = src.match(
    /(?:export )?const ALL_PLATFORM_FEATURES(?:: [^=]+)? = \[([\s\S]*?)\](?:\s+as const)?/,
  );
  const flags = new Set<string>();
  if (block) {
    for (const m of block[1].matchAll(/"([^"]+)"/g)) flags.add(m[1]);
  }
  const lines = [writeHeader("Feature flags (referenced in code)"), ""];
  lines.push(
    "Flags from `ALL_PLATFORM_FEATURES` in [`src/lib/db/settings.ts`](../../src/lib/db/settings.ts).",
  );
  lines.push("");
  if (flags.size === 0) {
    lines.push("_No flags found._");
  } else {
    for (const f of [...flags].sort()) lines.push(`- \`${f}\``);
  }
  writeFileSync(join(OUT, "feature-flags.md"), lines.join("\n"));
}

function genSkillsIndex() {
  const skillsDir = join(ROOT, ".cursor/skills");
  const lines = [writeHeader("Cursor skills index"), ""];
  lines.push("| Skill | Description |");
  lines.push("|-------|-------------|");
  for (const entry of readdirSync(skillsDir).sort()) {
    const p = join(skillsDir, entry, "SKILL.md");
    try {
      const src = readFileSync(p, "utf8");
      const first = src.split("\n").find((l) => l.trim().length > 0) ?? "";
      lines.push(`| [\`${entry}\`](../../.cursor/skills/${entry}/SKILL.md) | ${first.replace(/^#+\s*/, "").slice(0, 140)} |`);
    } catch {
      // skip directories without SKILL.md
    }
  }
  writeFileSync(join(OUT, "skills-index.md"), lines.join("\n"));
}

function main() {
  ensureDir(OUT);
  genDbSchema();
  genApiSurface();
  genCronRegistry();
  genFeatureFlags();
  genSkillsIndex();
   
  console.log("[knowledge:gen] wrote", OUT);
}

main();
