/**
 * Vendors Clara/Will EN system prompts for the admin catalog.
 * Vercel excludes external/ — snapshots keep /admin/ai-prompts working in production.
 *
 * Run after updating prompts in external/etracker or external/notetaker:
 *   npm run prompts:sync-external
 */

import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import {
  extractBacktickLiteral,
  extractConstTemplateLiteral,
  readSource,
} from "../src/lib/ai/extract-source-prompt";

const ROOT = process.cwd();
const OUT_DIR = join(ROOT, "src/lib/ai/external-agent-prompts");

function extractClaraEn(): string | null {
  const source = readSource("external/etracker/src/lib/ai/run-expense-agent.ts");
  if (!source) return null;
  const marker = "return `You are Clara, an AI financial assistant";
  const idx = source.indexOf(marker);
  if (idx < 0) return null;
  const start = source.indexOf("`", idx) + 1;
  return extractBacktickLiteral(source, start);
}

function writeSnapshot(name: string, exportName: string, body: string, sourceFile: string) {
  const content = `/** Auto-generated by \`npm run prompts:sync-external\`. Do not edit by hand. */
/** Source: ${sourceFile} */

export const ${exportName} = ${JSON.stringify(body)};
`;
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, `${name}.ts`), content, "utf-8");
}

const clara = extractClaraEn();
const will =
  extractConstTemplateLiteral(
    "external/notetaker/src/lib/ai/prompts/en.ts",
    "SYSTEM_PROMPT_EN",
  ) ?? null;

if (!clara) {
  console.error(
    "[prompts:sync-external] Clara prompt not found — initialize external/etracker submodule.",
  );
  process.exit(1);
}
if (!will) {
  console.error(
    "[prompts:sync-external] Will prompt not found — initialize external/notetaker submodule.",
  );
  process.exit(1);
}

writeSnapshot(
  "clara-en.snapshot",
  "CLARA_PROMPT_EN_SNAPSHOT",
  clara,
  "external/etracker/src/lib/ai/run-expense-agent.ts",
);
writeSnapshot(
  "will-en.snapshot",
  "WILL_PROMPT_EN_SNAPSHOT",
  will,
  "external/notetaker/src/lib/ai/prompts/en.ts",
);

console.log("[prompts:sync-external] wrote snapshots to src/lib/ai/external-agent-prompts/");
